// V2: only microbiology + chemistry categories.
// `name_sq` / `name_en` provide bilingual display; `description_sq` / `description_en` for tooltips/cards.

export const analysisCategories = [
  { id: "microbiology", labelKey: "categories.microbiology" },
  { id: "chemistry",    labelKey: "categories.chemistry" },
];

export const analyses = [
  // Microbiology
  {
    id: "salmonella",
    category: "microbiology",
    name_sq: "Salmonella spp.",
    name_en: "Salmonella spp.",
    method: "ISO 6579-1",
    duration_sq: "3–5 ditë pune",
    duration_en: "3–5 working days",
    description_sq: "Prania e Salmonella-s në mish, qumësht, perime dhe ushqime të gatshme.",
    description_en: "Salmonella presence in meat, dairy, vegetables and ready-to-eat foods.",
  },
  {
    id: "listeria",
    category: "microbiology",
    name_sq: "Listeria monocytogenes",
    name_en: "Listeria monocytogenes",
    method: "ISO 11290-1",
    duration_sq: "4–7 ditë pune",
    duration_en: "4–7 working days",
    description_sq: "Identifikim i Listeria-s në produkte të zinxhirit të ftohtë.",
    description_en: "Detection of Listeria in cold-chain products.",
  },
  {
    id: "ecoli",
    category: "microbiology",
    name_sq: "Escherichia coli (E. coli)",
    name_en: "Escherichia coli (E. coli)",
    method: "ISO 16649-2",
    duration_sq: "2–4 ditë pune",
    duration_en: "2–4 working days",
    description_sq: "Indikator i kontaminimit fekal dhe varianti patogjenik O157.",
    description_en: "Faecal contamination indicator and pathogenic O157 variant.",
  },
  {
    id: "staphylococcus",
    category: "microbiology",
    name_sq: "Staphylococcus aureus",
    name_en: "Staphylococcus aureus",
    method: "ISO 6888-1",
    duration_sq: "2–3 ditë pune",
    duration_en: "2–3 working days",
    description_sq: "Stafilokoket koagulazë-pozitive që prodhojnë toksina në produkte qumështi dhe mishi.",
    description_en: "Coagulase-positive toxin-producing staphylococci in dairy and meat.",
  },
  {
    id: "tpc",
    category: "microbiology",
    name_sq: "Numërimi total i bakterieve (TPC)",
    name_en: "Total Plate Count (TPC)",
    method: "ISO 4833-1",
    duration_sq: "2–3 ditë pune",
    duration_en: "2–3 working days",
    description_sq: "Tregues i përgjithshëm i ngarkesës mikrobiologjike.",
    description_en: "General indicator of microbiological load.",
  },
  {
    id: "yeast-mold",
    category: "microbiology",
    name_sq: "Mavija dhe maja",
    name_en: "Yeast and Mould",
    method: "ISO 21527-1/2",
    duration_sq: "5–7 ditë pune",
    duration_en: "5–7 working days",
    description_sq: "Numërim i mikroorganizmave që shkaktojnë prishje.",
    description_en: "Enumeration of spoilage microorganisms.",
  },
  {
    id: "enterobacteriaceae",
    category: "microbiology",
    name_sq: "Enterobacteriaceae",
    name_en: "Enterobacteriaceae",
    method: "ISO 21528-2",
    duration_sq: "2–3 ditë pune",
    duration_en: "2–3 working days",
    description_sq: "Familja e baktereve që tregon higjienë procesi.",
    description_en: "Family of bacteria indicating process hygiene.",
  },
  {
    id: "bacillus-cereus",
    category: "microbiology",
    name_sq: "Bacillus cereus",
    name_en: "Bacillus cereus",
    method: "ISO 7932",
    duration_sq: "2–3 ditë pune",
    duration_en: "2–3 working days",
    description_sq: "Bakter sporeformues që shkakton toksiinfeksion ushqimor.",
    description_en: "Spore-forming bacterium causing foodborne toxic infection.",
  },

  // Chemistry
  {
    id: "heavy-metals",
    category: "chemistry",
    name_sq: "Metale të rënda (Pb, Cd, Hg, As)",
    name_en: "Heavy metals (Pb, Cd, Hg, As)",
    method: "ICP-MS",
    duration_sq: "5–10 ditë pune",
    duration_en: "5–10 working days",
    description_sq: "Përcaktimi i plumbit, kadmiumit, mërkurit dhe arsenikut.",
    description_en: "Determination of lead, cadmium, mercury, arsenic.",
  },
  {
    id: "pesticide-residues",
    category: "chemistry",
    name_sq: "Mbetjet e pesticideve",
    name_en: "Pesticide residues",
    method: "LC-MS/MS · GC-MS/MS",
    duration_sq: "5–10 ditë pune",
    duration_en: "5–10 working days",
    description_sq: "Skrining me spektër të gjerë i mbetjeve të pesticideve.",
    description_en: "Broad-spectrum pesticide residue screening.",
  },
  {
    id: "additives",
    category: "chemistry",
    name_sq: "Aditivët ushqimorë",
    name_en: "Food additives",
    method: "HPLC-DAD",
    duration_sq: "5–7 ditë pune",
    duration_en: "5–7 working days",
    description_sq: "Konservantë, ngjyrues, ëmbëlsues.",
    description_en: "Preservatives, colorants, sweeteners.",
  },
  {
    id: "nutrition",
    category: "chemistry",
    name_sq: "Vlerat ushqyese",
    name_en: "Nutrition panel",
    method: "Multiple",
    duration_sq: "5–10 ditë pune",
    duration_en: "5–10 working days",
    description_sq: "Energjia, proteinat, yndyrnat, karbohidratet, fibrat, kripa.",
    description_en: "Energy, protein, fat, carbs, fibre, salt.",
  },
  {
    id: "moisture",
    category: "chemistry",
    name_sq: "Lagështia dhe lënda e thatë",
    name_en: "Moisture & dry matter",
    method: "Gravimetric",
    duration_sq: "2–3 ditë pune",
    duration_en: "2–3 working days",
    description_sq: "Përmbajtja e ujit dhe lëndës së thatë në produkt.",
    description_en: "Water and dry matter content.",
  },
  {
    id: "ph-acidity",
    category: "chemistry",
    name_sq: "pH dhe aciditeti",
    name_en: "pH & acidity",
    method: "Potentiometric",
    duration_sq: "1–2 ditë pune",
    duration_en: "1–2 working days",
    description_sq: "Vlera pH dhe aciditeti titrimetrik.",
    description_en: "pH value and titratable acidity.",
  },
  {
    id: "mycotoxins",
    category: "chemistry",
    name_sq: "Mykotoksinat (Aflatoksina, OTA)",
    name_en: "Mycotoxins (Aflatoxin, OTA)",
    method: "HPLC-FLD · LC-MS",
    duration_sq: "5–7 ditë pune",
    duration_en: "5–7 working days",
    description_sq: "Aflatoksinat dhe ochratoxina A në drithëra, frutat e thata, erëzat.",
    description_en: "Aflatoxins and ochratoxin A in grains, nuts, spices.",
  },
  {
    id: "salt",
    category: "chemistry",
    name_sq: "Përmbajtja e kripës (NaCl)",
    name_en: "Salt content (NaCl)",
    method: "Argentometric",
    duration_sq: "2–3 ditë pune",
    duration_en: "2–3 working days",
    description_sq: "Përmbajtja e klorurit të natriumit (NaCl).",
    description_en: "Sodium chloride content.",
  },
];

export function getAnalysisName(a, locale) {
  return locale === "en" ? a.name_en || a.name_sq : a.name_sq;
}
export function getAnalysisDescription(a, locale) {
  return locale === "en" ? a.description_en || a.description_sq : a.description_sq;
}
export function getAnalysisDuration(a, locale) {
  return locale === "en" ? a.duration_en || a.duration_sq : a.duration_sq;
}
