// V2: microbiology + physicochemical categories, across drinking water / food / wastewater matrices.
// `name_sq` / `name_en` provide bilingual display; `description_sq` / `description_en` for tooltips/cards.
// method (ISO) values are a starting suggestion — confirm with the lab.
// duration_* is intentionally "TODO" until the lab provides turnaround times.

export const analysisCategories = [
  { id: "microbiology",     labelKey: "categories.microbiology" },
  { id: "physicochemical",  labelKey: "categories.physicochemical" },
];

export const analysisMatrices = [
  { id: "drinking_water", labelKey: "analysesPage.matrices.drinking_water" },
  { id: "food",           labelKey: "analysesPage.matrices.food" },
  { id: "wastewater",     labelKey: "analysesPage.matrices.wastewater" },
];

export const analyses = [
  // ───────── MICROBIOLOGY — DRINKING WATER ─────────
  {
    id: "colony-count-22-37",
    category: "microbiology",
    matrix: "drinking_water",
    name_sq: "Numërimi i kolonive në 22°C dhe 37°C",
    name_en: "Colony count at 22°C and 37°C",
    method: "ISO 6222",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Ngarkesa e përgjithshme mikrobike e ujit në dy temperatura inkubimi.",
    description_en: "General microbial load of water at two incubation temperatures.",
  },
  {
    id: "total-coliforms",
    category: "microbiology",
    matrix: "drinking_water",
    name_sq: "Koliformët totalë",
    name_en: "Total coliforms",
    method: "ISO 9308-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Tregues higjiene për cilësinë e ujit dhe efikasitetin e trajtimit.",
    description_en: "Hygiene indicator for water quality and treatment efficiency.",
  },
  {
    id: "e-coli-water",
    category: "microbiology",
    matrix: "drinking_water",
    name_sq: "Escherichia coli",
    name_en: "Escherichia coli",
    method: "ISO 9308-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Tregues i kontaminimit të freskët fekal në ujë.",
    description_en: "Indicator of recent faecal contamination in water.",
  },
  {
    id: "intestinal-enterococci",
    category: "microbiology",
    matrix: "drinking_water",
    name_sq: "Enterokoket intestinale",
    name_en: "Intestinal enterococci",
    method: "ISO 7899-2",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Tregues fekal që konfirmon kontaminim të vazhdueshëm.",
    description_en: "Faecal indicator confirming persistent contamination.",
  },
  {
    id: "clostridium-perfringens",
    category: "microbiology",
    matrix: "drinking_water",
    name_sq: "Clostridium perfringens",
    name_en: "Clostridium perfringens",
    method: "ISO 14189",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Tregues i ndotjes fekale të vjetër dhe dështimeve të trajtimit.",
    description_en: "Indicator of older faecal pollution and treatment failures.",
  },

  // ───────── MICROBIOLOGY — FOOD ─────────
  {
    id: "aerobic-colony-count",
    category: "microbiology",
    matrix: "food",
    name_sq: "Numërimi aerob i kolonive",
    name_en: "Aerobic colony count",
    method: "ISO 4833-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Cilësia e përgjithshme mikrobiologjike dhe higjiena e produktit.",
    description_en: "Overall microbiological quality and hygiene of the product.",
  },
  {
    id: "enterobacteriaceae",
    category: "microbiology",
    matrix: "food",
    name_sq: "Enterobacteriaceae",
    name_en: "Enterobacteriaceae",
    method: "ISO 21528-2",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Familja e baktereve që tregon higjienën e procesit.",
    description_en: "Family of bacteria that indicates process hygiene.",
  },
  {
    id: "e-coli-food",
    category: "microbiology",
    matrix: "food",
    name_sq: "Escherichia coli (β-glukuronidazë pozitive)",
    name_en: "Escherichia coli (β-glucuronidase positive)",
    method: "ISO 16649-2",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Tregues i kontaminimit fekal në ushqim.",
    description_en: "Indicator of faecal contamination in food.",
  },
  {
    id: "coagulase-staph",
    category: "microbiology",
    matrix: "food",
    name_sq: "Stafilokoket koagulazë-pozitive",
    name_en: "Coagulase-positive Staphylococci",
    method: "ISO 6888-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Stafilokoket koagulazë-pozitive që prodhojnë toksina në produkte qumështi dhe mishi.",
    description_en: "Toxin-producing staphylococci in dairy and meat products.",
  },
  {
    id: "yeasts-moulds",
    category: "microbiology",
    matrix: "food",
    name_sq: "Maja dhe myk",
    name_en: "Yeasts and moulds",
    method: "ISO 21527-1/2",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Mikroorganizma prishjeje që ndikojnë në afatin e ruajtjes.",
    description_en: "Spoilage microorganisms affecting shelf life.",
  },
  {
    id: "salmonella",
    category: "microbiology",
    matrix: "food",
    name_sq: "Salmonella spp.",
    name_en: "Salmonella spp.",
    method: "ISO 6579-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Zbulimi i Salmonella-s, patogjen kryesor ushqimor.",
    description_en: "Detection of Salmonella, a major foodborne pathogen.",
  },
  {
    id: "listeria",
    category: "microbiology",
    matrix: "food",
    name_sq: "Listeria monocytogenes",
    name_en: "Listeria monocytogenes",
    method: "ISO 11290-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Identifikim i Listeria-s në produkte të zinxhirit të ftohtë dhe gati për konsum.",
    description_en: "Detection of Listeria in chilled and ready-to-eat foods.",
  },

  // ───────── PHYSICOCHEMICAL — DRINKING WATER ─────────
  {
    id: "ph",
    category: "physicochemical",
    matrix: "drinking_water",
    name_sq: "pH",
    name_en: "pH",
    method: "ISO 10523",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Aciditeti ose alkaliniteti i mostrës.",
    description_en: "Acidity or alkalinity of the sample.",
  },
  {
    id: "conductivity",
    category: "physicochemical",
    matrix: "drinking_water",
    name_sq: "Përçueshmëria elektrike",
    name_en: "Conductivity",
    method: "ISO 7888",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Përçueshmëria elektrike, tregues i kripërave të tretura.",
    description_en: "Electrical conductivity, an indicator of dissolved salts.",
  },
  {
    id: "turbidity",
    category: "physicochemical",
    matrix: "drinking_water",
    name_sq: "Turbullira",
    name_en: "Turbidity",
    method: "ISO 7027-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Turbullira e shkaktuar nga grimcat pezull.",
    description_en: "Cloudiness caused by suspended particles.",
  },
  {
    id: "nitrate-nitrogen",
    category: "physicochemical",
    matrix: "drinking_water",
    name_sq: "Azoti nitrat (NO₃-N)",
    name_en: "Nitrate nitrogen (NO₃-N)",
    method: "TODO",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Përmbajtja e nitrateve, e rëndësishme për cilësinë e ujit dhe ndotjen.",
    description_en: "Nitrate content, relevant to water quality and pollution.",
  },
  {
    id: "nitrite-nitrogen",
    category: "physicochemical",
    matrix: "drinking_water",
    name_sq: "Azoti nitrit (NO₂-N)",
    name_en: "Nitrite nitrogen (NO₂-N)",
    method: "ISO 26777",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Përmbajtja e nitriteve, tregues kontaminimi.",
    description_en: "Nitrite content, an indicator of contamination.",
  },
  {
    id: "ammoniacal-nitrogen",
    category: "physicochemical",
    matrix: "drinking_water",
    name_sq: "Azoti amoniakal (NH₄-N)",
    name_en: "Ammoniacal nitrogen (NH₄-N)",
    method: "ISO 7150-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Përmbajtja e amoniumit, shenjë e ndotjes organike.",
    description_en: "Ammonium content, a sign of organic pollution.",
  },
  {
    id: "total-phosphorus",
    category: "physicochemical",
    matrix: "drinking_water",
    name_sq: "Fosfori total",
    name_en: "Total phosphorus",
    method: "ISO 6878",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Fosfori total, parametër kyç i eutrofikimit.",
    description_en: "Total phosphorus, a key eutrophication parameter.",
  },
  {
    id: "total-solids",
    category: "physicochemical",
    matrix: "drinking_water",
    name_sq: "Lëndët e ngurta totale",
    name_en: "Total solids",
    method: "TODO",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Lëndët e ngurta totale të tretura dhe pezull në mostër.",
    description_en: "Total dissolved and suspended solids in the sample.",
  },

  // ───────── PHYSICOCHEMICAL — WASTEWATER ─────────
  {
    id: "bod5",
    category: "physicochemical",
    matrix: "wastewater",
    name_sq: "BOD₅ (Kërkesa biokimike për oksigjen)",
    name_en: "BOD₅",
    method: "ISO 5815-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Kërkesa biokimike për oksigjen gjatë pesë ditëve.",
    description_en: "Biochemical oxygen demand over five days.",
  },
  {
    id: "cod",
    category: "physicochemical",
    matrix: "wastewater",
    name_sq: "COD (Kërkesa kimike për oksigjen)",
    name_en: "COD",
    method: "ISO 6060",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Kërkesa kimike për oksigjen, masë e ngarkesës organike.",
    description_en: "Chemical oxygen demand, a measure of organic load.",
  },
  {
    id: "surfactants",
    category: "physicochemical",
    matrix: "wastewater",
    name_sq: "Surfaktantët",
    name_en: "Surfactants",
    method: "ISO 7875-1",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Surfaktantët anionikë (detergjentët) në ujërat e zeza.",
    description_en: "Anionic surfactants (detergents) in wastewater.",
  },

  // ───────── PHYSICOCHEMICAL — FOOD ─────────
  {
    id: "moisture",
    category: "physicochemical",
    matrix: "food",
    name_sq: "Lagështia",
    name_en: "Moisture",
    method: "TODO",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Përmbajtja e ujit në mostrën ushqimore.",
    description_en: "Water content of the food sample.",
  },
  {
    id: "ash",
    category: "physicochemical",
    matrix: "food",
    name_sq: "Hiri",
    name_en: "Ash",
    method: "TODO",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Përmbajtja totale minerale pas djegies.",
    description_en: "Total mineral content after incineration.",
  },
  {
    id: "protein-kjeldahl",
    category: "physicochemical",
    matrix: "food",
    name_sq: "Proteina (Kjeldahl)",
    name_en: "Protein (Kjeldahl)",
    method: "TODO",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Përmbajtja totale e proteinave me metodën Kjeldahl.",
    description_en: "Total protein content by the Kjeldahl method.",
  },
  {
    id: "total-fat",
    category: "physicochemical",
    matrix: "food",
    name_sq: "Yndyra totale",
    name_en: "Total Fat",
    method: "TODO",
    duration_sq: "TODO",
    duration_en: "TODO",
    description_sq: "Përmbajtja totale e yndyrës në produkt.",
    description_en: "Total fat content of the product.",
  },
];

export function getAnalysisName(a, locale) {
  return locale === "en" ? a.name_en || a.name_sq : a.name_sq;
}
export function getAnalysisDescription(a, locale) {
  return locale === "en" ? a.description_en || a.description_sq : a.description_sq;
}
export function getAnalysisDuration(a, locale) {
  return locale === "en" ? a.duration_en || a.duration_sq : a.duration_sq;
}
